// Code generated by 'yaegi extract github.com/injoyai/ios/server'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/server"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/server/server"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New":        reflect.ValueOf(server.New),
		"Run":        reflect.ValueOf(server.Run),
		"RunContext": reflect.ValueOf(server.RunContext),

		// type definitions
		"Event":  reflect.ValueOf((*server.Event)(nil)),
		"Option": reflect.ValueOf((*server.Option)(nil)),
		"Server": reflect.ValueOf((*server.Server)(nil)),
	}
}
