// Code generated by 'yaegi extract github.com/injoyai/ios/module/rabbitmq'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/module/rabbitmq"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/module/rabbitmq/rabbitmq"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":            reflect.ValueOf(rabbitmq.Dial),
		"DialConnect":     reflect.ValueOf(rabbitmq.DialConnect),
		"DialWithContext": reflect.ValueOf(rabbitmq.DialWithContext),
		"NewDial":         reflect.ValueOf(rabbitmq.NewDial),

		// type definitions
		"Client":  reflect.ValueOf((*rabbitmq.Client)(nil)),
		"Config":  reflect.ValueOf((*rabbitmq.Config)(nil)),
		"Message": reflect.ValueOf((*rabbitmq.Message)(nil)),
	}
}
