// Code generated by 'yaegi extract github.com/injoyai/ios'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios"
	"go/constant"
	"go/token"
	"io"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/ios"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bridge":                reflect.ValueOf(ios.Bridge),
		"CheckReader":           reflect.ValueOf(ios.CheckReader),
		"Copy":                  reflect.ValueOf(ios.Copy),
		"CopyBuffer":            reflect.ValueOf(ios.CopyBuffer),
		"CopyBufferWith":        reflect.ValueOf(ios.CopyBufferWith),
		"CopyWith":              reflect.ValueOf(ios.CopyWith),
		"DefaultBufferSize":     reflect.ValueOf(constant.MakeFromLiteral("4096", token.INT, 0)),
		"ErrCloseClose":         reflect.ValueOf(&ios.ErrCloseClose).Elem(),
		"ErrHandClose":          reflect.ValueOf(&ios.ErrHandClose).Elem(),
		"ErrInvalidReadFunc":    reflect.ValueOf(&ios.ErrInvalidReadFunc).Elem(),
		"ErrMaxConnect":         reflect.ValueOf(&ios.ErrMaxConnect).Elem(),
		"ErrNetworkUnusual":     reflect.ValueOf(&ios.ErrNetworkUnusual).Elem(),
		"ErrPortNull":           reflect.ValueOf(&ios.ErrPortNull).Elem(),
		"ErrReadClosed":         reflect.ValueOf(&ios.ErrReadClosed).Elem(),
		"ErrReadTimeout":        reflect.ValueOf(&ios.ErrReadTimeout).Elem(),
		"ErrRemoteClose":        reflect.ValueOf(&ios.ErrRemoteClose).Elem(),
		"ErrRemoteCloseUnusual": reflect.ValueOf(&ios.ErrRemoteCloseUnusual).Elem(),
		"ErrRemoteOff":          reflect.ValueOf(&ios.ErrRemoteOff).Elem(),
		"ErrUnknownReader":      reflect.ValueOf(&ios.ErrUnknownReader).Elem(),
		"ErrUseReadAck":         reflect.ValueOf(&ios.ErrUseReadAck).Elem(),
		"ErrUseReadMessage":     reflect.ValueOf(&ios.ErrUseReadMessage).Elem(),
		"ErrWithConnectTimeout": reflect.ValueOf(&ios.ErrWithConnectTimeout).Elem(),
		"ErrWithContext":        reflect.ValueOf(&ios.ErrWithContext).Elem(),
		"ErrWithTimeout":        reflect.ValueOf(&ios.ErrWithTimeout).Elem(),
		"ErrWriteClosed":        reflect.ValueOf(&ios.ErrWriteClosed).Elem(),
		"ErrWriteTimeout":       reflect.ValueOf(&ios.ErrWriteTimeout).Elem(),
		"MultiCloser":           reflect.ValueOf(ios.MultiCloser),
		"NewAllReader":          reflect.ValueOf(ios.NewAllReader),
		"NewBufferReader":       reflect.ValueOf(ios.NewBufferReader),
		"NewFRead":              reflect.ValueOf(ios.NewFRead),
		"NewFRead2":             reflect.ValueOf(ios.NewFRead2),
		"NewFRead2WithHandler":  reflect.ValueOf(ios.NewFRead2WithHandler),
		"NewFRead4KB":           reflect.ValueOf(ios.NewFRead4KB),
		"NewFReadKB":            reflect.ValueOf(ios.NewFReadKB),
		"NewFReadLeast":         reflect.ValueOf(ios.NewFReadLeast),
		"NewMReaderWithChan":    reflect.ValueOf(ios.NewMReaderWithChan),
		"NewMoreWrite":          reflect.ValueOf(ios.NewMoreWrite),
		"NewPiper":              reflect.ValueOf(ios.NewPiper),
		"Null":                  reflect.ValueOf(&ios.Null).Elem(),
		"Pipe":                  reflect.ValueOf(ios.Pipe),
		"ReadBuffer":            reflect.ValueOf(ios.ReadBuffer),
		"ReadByte":              reflect.ValueOf(ios.ReadByte),
		"ReadPrefix":            reflect.ValueOf(ios.ReadPrefix),
		"Reverse":               reflect.ValueOf(ios.Reverse),
		"SplitBytesByLength":    reflect.ValueOf(ios.SplitBytesByLength),
		"Swap":                  reflect.ValueOf(ios.Swap),

		// type definitions
		"AReadCloser":        reflect.ValueOf((*ios.AReadCloser)(nil)),
		"AReadFunc":          reflect.ValueOf((*ios.AReadFunc)(nil)),
		"AReadWriteCloser":   reflect.ValueOf((*ios.AReadWriteCloser)(nil)),
		"AReadWriter":        reflect.ValueOf((*ios.AReadWriter)(nil)),
		"AReader":            reflect.ValueOf((*ios.AReader)(nil)),
		"Ack":                reflect.ValueOf((*ios.Ack)(nil)),
		"Acker":              reflect.ValueOf((*ios.Acker)(nil)),
		"AllReadWriteCloser": reflect.ValueOf((*ios.AllReadWriteCloser)(nil)),
		"AllReader":          reflect.ValueOf((*ios.AllReader)(nil)),
		"AnyWriter":          reflect.ValueOf((*ios.AnyWriter)(nil)),
		"Base64Writer":       reflect.ValueOf((*ios.Base64Writer)(nil)),
		"Buffer":             reflect.ValueOf((*ios.Buffer)(nil)),
		"BufferReader":       reflect.ValueOf((*ios.BufferReader)(nil)),
		"ChanWriter":         reflect.ValueOf((*ios.ChanWriter)(nil)),
		"Checker":            reflect.ValueOf((*ios.Checker)(nil)),
		"CloseFunc":          reflect.ValueOf((*ios.CloseFunc)(nil)),
		"Closer":             reflect.ValueOf((*ios.Closer)(nil)),
		"DialFunc":           reflect.ValueOf((*ios.DialFunc)(nil)),
		"FRead2Func":         reflect.ValueOf((*ios.FRead2Func)(nil)),
		"FReadFunc":          reflect.ValueOf((*ios.FReadFunc)(nil)),
		"FReader":            reflect.ValueOf((*ios.FReader)(nil)),
		"HEXWriter":          reflect.ValueOf((*ios.HEXWriter)(nil)),
		"IO":                 reflect.ValueOf((*ios.IO)(nil)),
		"IOer":               reflect.ValueOf((*ios.IOer)(nil)),
		"JsonWriter":         reflect.ValueOf((*ios.JsonWriter)(nil)),
		"ListenFunc":         reflect.ValueOf((*ios.ListenFunc)(nil)),
		"Listener":           reflect.ValueOf((*ios.Listener)(nil)),
		"MReadCloser":        reflect.ValueOf((*ios.MReadCloser)(nil)),
		"MReadFunc":          reflect.ValueOf((*ios.MReadFunc)(nil)),
		"MReadWriteCloser":   reflect.ValueOf((*ios.MReadWriteCloser)(nil)),
		"MReadWriter":        reflect.ValueOf((*ios.MReadWriter)(nil)),
		"MReader":            reflect.ValueOf((*ios.MReader)(nil)),
		"MoreRead":           reflect.ValueOf((*ios.MoreRead)(nil)),
		"MoreWrite":          reflect.ValueOf((*ios.MoreWrite)(nil)),
		"MoreWriter":         reflect.ValueOf((*ios.MoreWriter)(nil)),
		"Piper":              reflect.ValueOf((*ios.Piper)(nil)),
		"Plan":               reflect.ValueOf((*ios.Plan)(nil)),
		"PlanWrite":          reflect.ValueOf((*ios.PlanWrite)(nil)),
		"ReadCloser":         reflect.ValueOf((*ios.ReadCloser)(nil)),
		"ReadFunc":           reflect.ValueOf((*ios.ReadFunc)(nil)),
		"ReadWriteCloser":    reflect.ValueOf((*ios.ReadWriteCloser)(nil)),
		"Reader":             reflect.ValueOf((*ios.Reader)(nil)),
		"Split":              reflect.ValueOf((*ios.Split)(nil)),
		"SplitLength":        reflect.ValueOf((*ios.SplitLength)(nil)),
		"SplitStartEnd":      reflect.ValueOf((*ios.SplitStartEnd)(nil)),
		"SplitTotal":         reflect.ValueOf((*ios.SplitTotal)(nil)),
		"WriteFunc":          reflect.ValueOf((*ios.WriteFunc)(nil)),
		"WriteOption":        reflect.ValueOf((*ios.WriteOption)(nil)),
		"WriteResult":        reflect.ValueOf((*ios.WriteResult)(nil)),

		// interface wrapper definitions
		"_AReadCloser":        reflect.ValueOf((*_github_com_injoyai_ios_AReadCloser)(nil)),
		"_AReadWriteCloser":   reflect.ValueOf((*_github_com_injoyai_ios_AReadWriteCloser)(nil)),
		"_AReadWriter":        reflect.ValueOf((*_github_com_injoyai_ios_AReadWriter)(nil)),
		"_AReader":            reflect.ValueOf((*_github_com_injoyai_ios_AReader)(nil)),
		"_Acker":              reflect.ValueOf((*_github_com_injoyai_ios_Acker)(nil)),
		"_AllReadWriteCloser": reflect.ValueOf((*_github_com_injoyai_ios_AllReadWriteCloser)(nil)),
		"_AllReader":          reflect.ValueOf((*_github_com_injoyai_ios_AllReader)(nil)),
		"_AnyWriter":          reflect.ValueOf((*_github_com_injoyai_ios_AnyWriter)(nil)),
		"_Base64Writer":       reflect.ValueOf((*_github_com_injoyai_ios_Base64Writer)(nil)),
		"_ChanWriter":         reflect.ValueOf((*_github_com_injoyai_ios_ChanWriter)(nil)),
		"_Checker":            reflect.ValueOf((*_github_com_injoyai_ios_Checker)(nil)),
		"_Closer":             reflect.ValueOf((*_github_com_injoyai_ios_Closer)(nil)),
		"_FReader":            reflect.ValueOf((*_github_com_injoyai_ios_FReader)(nil)),
		"_HEXWriter":          reflect.ValueOf((*_github_com_injoyai_ios_HEXWriter)(nil)),
		"_IO":                 reflect.ValueOf((*_github_com_injoyai_ios_IO)(nil)),
		"_JsonWriter":         reflect.ValueOf((*_github_com_injoyai_ios_JsonWriter)(nil)),
		"_Listener":           reflect.ValueOf((*_github_com_injoyai_ios_Listener)(nil)),
		"_MReadCloser":        reflect.ValueOf((*_github_com_injoyai_ios_MReadCloser)(nil)),
		"_MReadWriteCloser":   reflect.ValueOf((*_github_com_injoyai_ios_MReadWriteCloser)(nil)),
		"_MReadWriter":        reflect.ValueOf((*_github_com_injoyai_ios_MReadWriter)(nil)),
		"_MReader":            reflect.ValueOf((*_github_com_injoyai_ios_MReader)(nil)),
		"_MoreWriter":         reflect.ValueOf((*_github_com_injoyai_ios_MoreWriter)(nil)),
		"_ReadCloser":         reflect.ValueOf((*_github_com_injoyai_ios_ReadCloser)(nil)),
		"_ReadWriteCloser":    reflect.ValueOf((*_github_com_injoyai_ios_ReadWriteCloser)(nil)),
		"_Reader":             reflect.ValueOf((*_github_com_injoyai_ios_Reader)(nil)),
	}
}

// _github_com_injoyai_ios_AReadCloser is an interface wrapper for AReadCloser type
type _github_com_injoyai_ios_AReadCloser struct {
	IValue   interface{}
	WClose   func() error
	WReadAck func() (ios.Acker, error)
}

func (W _github_com_injoyai_ios_AReadCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_AReadCloser) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}

// _github_com_injoyai_ios_AReadWriteCloser is an interface wrapper for AReadWriteCloser type
type _github_com_injoyai_ios_AReadWriteCloser struct {
	IValue   interface{}
	WClose   func() error
	WReadAck func() (ios.Acker, error)
	WWrite   func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_AReadWriteCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_AReadWriteCloser) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}
func (W _github_com_injoyai_ios_AReadWriteCloser) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_AReadWriter is an interface wrapper for AReadWriter type
type _github_com_injoyai_ios_AReadWriter struct {
	IValue   interface{}
	WReadAck func() (ios.Acker, error)
	WWrite   func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_AReadWriter) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}
func (W _github_com_injoyai_ios_AReadWriter) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_AReader is an interface wrapper for AReader type
type _github_com_injoyai_ios_AReader struct {
	IValue   interface{}
	WReadAck func() (ios.Acker, error)
}

func (W _github_com_injoyai_ios_AReader) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}

// _github_com_injoyai_ios_Acker is an interface wrapper for Acker type
type _github_com_injoyai_ios_Acker struct {
	IValue   interface{}
	WAck     func() error
	WPayload func() []byte
}

func (W _github_com_injoyai_ios_Acker) Ack() error {
	return W.WAck()
}
func (W _github_com_injoyai_ios_Acker) Payload() []byte {
	return W.WPayload()
}

// _github_com_injoyai_ios_AllReadWriteCloser is an interface wrapper for AllReadWriteCloser type
type _github_com_injoyai_ios_AllReadWriteCloser struct {
	IValue       interface{}
	WClose       func() error
	WRead        func(p []byte) (n int, err error)
	WReadAck     func() (ios.Acker, error)
	WReadMessage func() ([]byte, error)
	WWrite       func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_AllReadWriteCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_AllReadWriteCloser) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_injoyai_ios_AllReadWriteCloser) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}
func (W _github_com_injoyai_ios_AllReadWriteCloser) ReadMessage() ([]byte, error) {
	return W.WReadMessage()
}
func (W _github_com_injoyai_ios_AllReadWriteCloser) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_AllReader is an interface wrapper for AllReader type
type _github_com_injoyai_ios_AllReader struct {
	IValue       interface{}
	WRead        func(p []byte) (n int, err error)
	WReadAck     func() (ios.Acker, error)
	WReadMessage func() ([]byte, error)
}

func (W _github_com_injoyai_ios_AllReader) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_injoyai_ios_AllReader) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}
func (W _github_com_injoyai_ios_AllReader) ReadMessage() ([]byte, error) {
	return W.WReadMessage()
}

// _github_com_injoyai_ios_AnyWriter is an interface wrapper for AnyWriter type
type _github_com_injoyai_ios_AnyWriter struct {
	IValue    interface{}
	WWriteAny func(a any) error
}

func (W _github_com_injoyai_ios_AnyWriter) WriteAny(a any) error {
	return W.WWriteAny(a)
}

// _github_com_injoyai_ios_Base64Writer is an interface wrapper for Base64Writer type
type _github_com_injoyai_ios_Base64Writer struct {
	IValue       interface{}
	WWriteBase64 func(s string) error
}

func (W _github_com_injoyai_ios_Base64Writer) WriteBase64(s string) error {
	return W.WWriteBase64(s)
}

// _github_com_injoyai_ios_ChanWriter is an interface wrapper for ChanWriter type
type _github_com_injoyai_ios_ChanWriter struct {
	IValue     interface{}
	WWriteChan func(c chan any) error
}

func (W _github_com_injoyai_ios_ChanWriter) WriteChan(c chan any) error {
	return W.WWriteChan(c)
}

// _github_com_injoyai_ios_Checker is an interface wrapper for Checker type
type _github_com_injoyai_ios_Checker struct {
	IValue interface{}
	WCheck func(a0 []byte) (bool, bool)
}

func (W _github_com_injoyai_ios_Checker) Check(a0 []byte) (bool, bool) {
	return W.WCheck(a0)
}

// _github_com_injoyai_ios_Closer is an interface wrapper for Closer type
type _github_com_injoyai_ios_Closer struct {
	IValue  interface{}
	WClose  func() error
	WClosed func() bool
}

func (W _github_com_injoyai_ios_Closer) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_Closer) Closed() bool {
	return W.WClosed()
}

// _github_com_injoyai_ios_FReader is an interface wrapper for FReader type
type _github_com_injoyai_ios_FReader struct {
	IValue    interface{}
	WReadFrom func(r io.Reader) ([]byte, error)
}

func (W _github_com_injoyai_ios_FReader) ReadFrom(r io.Reader) ([]byte, error) {
	return W.WReadFrom(r)
}

// _github_com_injoyai_ios_HEXWriter is an interface wrapper for HEXWriter type
type _github_com_injoyai_ios_HEXWriter struct {
	IValue    interface{}
	WWriteHEX func(s string) error
}

func (W _github_com_injoyai_ios_HEXWriter) WriteHEX(s string) error {
	return W.WWriteHEX(s)
}

// _github_com_injoyai_ios_IO is an interface wrapper for IO type
type _github_com_injoyai_ios_IO struct {
	IValue       interface{}
	WClose       func() error
	WRead        func(p []byte) (n int, err error)
	WReadAck     func() (ios.Acker, error)
	WReadMessage func() ([]byte, error)
	WWrite       func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_IO) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_IO) Read(p []byte) (n int, err error) {
	return W.WRead(p)
}
func (W _github_com_injoyai_ios_IO) ReadAck() (ios.Acker, error) {
	return W.WReadAck()
}
func (W _github_com_injoyai_ios_IO) ReadMessage() ([]byte, error) {
	return W.WReadMessage()
}
func (W _github_com_injoyai_ios_IO) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_JsonWriter is an interface wrapper for JsonWriter type
type _github_com_injoyai_ios_JsonWriter struct {
	IValue     interface{}
	WWriteJson func(a any) error
}

func (W _github_com_injoyai_ios_JsonWriter) WriteJson(a any) error {
	return W.WWriteJson(a)
}

// _github_com_injoyai_ios_Listener is an interface wrapper for Listener type
type _github_com_injoyai_ios_Listener struct {
	IValue  interface{}
	WAccept func() (ios.ReadWriteCloser, string, error)
	WAddr   func() string
	WClose  func() error
}

func (W _github_com_injoyai_ios_Listener) Accept() (ios.ReadWriteCloser, string, error) {
	return W.WAccept()
}
func (W _github_com_injoyai_ios_Listener) Addr() string {
	return W.WAddr()
}
func (W _github_com_injoyai_ios_Listener) Close() error {
	return W.WClose()
}

// _github_com_injoyai_ios_MReadCloser is an interface wrapper for MReadCloser type
type _github_com_injoyai_ios_MReadCloser struct {
	IValue       interface{}
	WClose       func() error
	WReadMessage func() ([]byte, error)
}

func (W _github_com_injoyai_ios_MReadCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_MReadCloser) ReadMessage() ([]byte, error) {
	return W.WReadMessage()
}

// _github_com_injoyai_ios_MReadWriteCloser is an interface wrapper for MReadWriteCloser type
type _github_com_injoyai_ios_MReadWriteCloser struct {
	IValue       interface{}
	WClose       func() error
	WReadMessage func() ([]byte, error)
	WWrite       func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_MReadWriteCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_MReadWriteCloser) ReadMessage() ([]byte, error) {
	return W.WReadMessage()
}
func (W _github_com_injoyai_ios_MReadWriteCloser) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_MReadWriter is an interface wrapper for MReadWriter type
type _github_com_injoyai_ios_MReadWriter struct {
	IValue       interface{}
	WReadMessage func() ([]byte, error)
	WWrite       func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_MReadWriter) ReadMessage() ([]byte, error) {
	return W.WReadMessage()
}
func (W _github_com_injoyai_ios_MReadWriter) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_MReader is an interface wrapper for MReader type
type _github_com_injoyai_ios_MReader struct {
	IValue       interface{}
	WReadMessage func() ([]byte, error)
}

func (W _github_com_injoyai_ios_MReader) ReadMessage() ([]byte, error) {
	return W.WReadMessage()
}

// _github_com_injoyai_ios_MoreWriter is an interface wrapper for MoreWriter type
type _github_com_injoyai_ios_MoreWriter struct {
	IValue       interface{}
	WWrite       func(p []byte) (n int, err error)
	WWriteAny    func(a any) error
	WWriteBase64 func(s string) error
	WWriteByte   func(c byte) error
	WWriteChan   func(c chan any) error
	WWriteHEX    func(s string) error
	WWriteJson   func(a any) error
	WWriteString func(s string) (n int, err error)
}

func (W _github_com_injoyai_ios_MoreWriter) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}
func (W _github_com_injoyai_ios_MoreWriter) WriteAny(a any) error {
	return W.WWriteAny(a)
}
func (W _github_com_injoyai_ios_MoreWriter) WriteBase64(s string) error {
	return W.WWriteBase64(s)
}
func (W _github_com_injoyai_ios_MoreWriter) WriteByte(c byte) error {
	return W.WWriteByte(c)
}
func (W _github_com_injoyai_ios_MoreWriter) WriteChan(c chan any) error {
	return W.WWriteChan(c)
}
func (W _github_com_injoyai_ios_MoreWriter) WriteHEX(s string) error {
	return W.WWriteHEX(s)
}
func (W _github_com_injoyai_ios_MoreWriter) WriteJson(a any) error {
	return W.WWriteJson(a)
}
func (W _github_com_injoyai_ios_MoreWriter) WriteString(s string) (n int, err error) {
	return W.WWriteString(s)
}

// _github_com_injoyai_ios_ReadCloser is an interface wrapper for ReadCloser type
type _github_com_injoyai_ios_ReadCloser struct {
	IValue interface{}
	WClose func() error
}

func (W _github_com_injoyai_ios_ReadCloser) Close() error {
	return W.WClose()
}

// _github_com_injoyai_ios_ReadWriteCloser is an interface wrapper for ReadWriteCloser type
type _github_com_injoyai_ios_ReadWriteCloser struct {
	IValue interface{}
	WClose func() error
	WWrite func(p []byte) (n int, err error)
}

func (W _github_com_injoyai_ios_ReadWriteCloser) Close() error {
	return W.WClose()
}
func (W _github_com_injoyai_ios_ReadWriteCloser) Write(p []byte) (n int, err error) {
	return W.WWrite(p)
}

// _github_com_injoyai_ios_Reader is an interface wrapper for Reader type
type _github_com_injoyai_ios_Reader struct {
	IValue interface{}
}
