// Code generated by 'yaegi extract github.com/injoyai/ios/client/frame'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/client/frame"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/client/frame/frame"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ControlBack":         reflect.ValueOf(frame.ControlBack),
		"ControlCall":         reflect.ValueOf(frame.ControlCall),
		"ControlGzip":         reflect.ValueOf(frame.ControlGzip),
		"DealWith":            reflect.ValueOf(frame.DealWith),
		"Decode":              reflect.ValueOf(frame.Decode),
		"Default":             reflect.ValueOf(&frame.Default).Elem(),
		"FunctionCustom":      reflect.ValueOf(frame.FunctionCustom),
		"FunctionICCID":       reflect.ValueOf(frame.FunctionICCID),
		"FunctionIMEI":        reflect.ValueOf(frame.FunctionIMEI),
		"FunctionIMSI":        reflect.ValueOf(frame.FunctionIMSI),
		"FunctionLinkAddress": reflect.ValueOf(frame.FunctionLinkAddress),
		"FunctionPing":        reflect.ValueOf(frame.FunctionPing),
		"FunctionRead":        reflect.ValueOf(frame.FunctionRead),
		"FunctionReboot":      reflect.ValueOf(frame.FunctionReboot),
		"FunctionReload":      reflect.ValueOf(frame.FunctionReload),
		"FunctionSlave":       reflect.ValueOf(frame.FunctionSlave),
		"FunctionSubscribe":   reflect.ValueOf(frame.FunctionSubscribe),
		"FunctionTime":        reflect.ValueOf(frame.FunctionTime),
		"FunctionWrite":       reflect.ValueOf(frame.FunctionWrite),
		"New":                 reflect.ValueOf(frame.New),
		"NewBack":             reflect.ValueOf(frame.NewBack),
		"NewCall":             reflect.ValueOf(frame.NewCall),
		"NewPing":             reflect.ValueOf(frame.NewPing),
		"NewPong":             reflect.ValueOf(frame.NewPong),
		"ReadFrom":            reflect.ValueOf(frame.ReadFrom),
		"WriteWith":           reflect.ValueOf(frame.WriteWith),

		// type definitions
		"Frame": reflect.ValueOf((*frame.Frame)(nil)),
	}
}
