// Code generated by 'yaegi extract github.com/injoyai/tdx/protocol'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/base/types"
	"github.com/injoyai/tdx/protocol"

	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/tdx/protocol/protocol"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddPrefix":              reflect.ValueOf(protocol.AddPrefix),
		"Bytes":                  reflect.ValueOf(protocol.Bytes),
		"Control01":              reflect.ValueOf(protocol.Control01),
		"CutInt":                 reflect.ValueOf(protocol.CutInt),
		"Decode":                 reflect.ValueOf(protocol.Decode),
		"DecodeCode":             reflect.ValueOf(protocol.DecodeCode),
		"DecodeK":                reflect.ValueOf(protocol.DecodeK),
		"ExchangeBJ":             reflect.ValueOf(protocol.ExchangeBJ),
		"ExchangeEstablish":      reflect.ValueOf(&protocol.ExchangeEstablish).Elem(),
		"ExchangeSH":             reflect.ValueOf(protocol.ExchangeSH),
		"ExchangeSZ":             reflect.ValueOf(protocol.ExchangeSZ),
		"FixKlineTime":           reflect.ValueOf(protocol.FixKlineTime),
		"FloatUnit":              reflect.ValueOf(protocol.FloatUnit),
		"FloatUnitString":        reflect.ValueOf(protocol.FloatUnitString),
		"GetHourMinute":          reflect.ValueOf(protocol.GetHourMinute),
		"GetPrice":               reflect.ValueOf(protocol.GetPrice),
		"GetTime":                reflect.ValueOf(protocol.GetTime),
		"Int64UnitString":        reflect.ValueOf(protocol.Int64UnitString),
		"IntUnitString":          reflect.ValueOf(protocol.IntUnitString),
		"IsBJStock":              reflect.ValueOf(protocol.IsBJStock),
		"IsETF":                  reflect.ValueOf(protocol.IsETF),
		"IsIndex":                reflect.ValueOf(protocol.IsIndex),
		"IsSHStock":              reflect.ValueOf(protocol.IsSHStock),
		"IsSZStock":              reflect.ValueOf(protocol.IsSZStock),
		"IsStock":                reflect.ValueOf(protocol.IsStock),
		"KindIndex":              reflect.ValueOf(constant.MakeFromLiteral("\"index\"", token.STRING, 0)),
		"KindStock":              reflect.ValueOf(constant.MakeFromLiteral("\"stock\"", token.STRING, 0)),
		"MCallAuction":           reflect.ValueOf(&protocol.MCallAuction).Elem(),
		"MCode":                  reflect.ValueOf(&protocol.MCode).Elem(),
		"MConnect":               reflect.ValueOf(&protocol.MConnect).Elem(),
		"MCount":                 reflect.ValueOf(&protocol.MCount).Elem(),
		"MGbbq":                  reflect.ValueOf(&protocol.MGbbq).Elem(),
		"MHeart":                 reflect.ValueOf(&protocol.MHeart).Elem(),
		"MHistoryMinute":         reflect.ValueOf(&protocol.MHistoryMinute).Elem(),
		"MHistoryTrade":          reflect.ValueOf(&protocol.MHistoryTrade).Elem(),
		"MKline":                 reflect.ValueOf(&protocol.MKline).Elem(),
		"MMinute":                reflect.ValueOf(&protocol.MMinute).Elem(),
		"MQuote":                 reflect.ValueOf(&protocol.MQuote).Elem(),
		"MTrade":                 reflect.ValueOf(&protocol.MTrade).Elem(),
		"Prefix":                 reflect.ValueOf(constant.MakeFromLiteral("12", token.INT, 0)),
		"PrefixResp":             reflect.ValueOf(constant.MakeFromLiteral("2982900736", token.INT, 0)),
		"ReadFrom":               reflect.ValueOf(protocol.ReadFrom),
		"Reverse":                reflect.ValueOf(protocol.Reverse),
		"String":                 reflect.ValueOf(protocol.String),
		"TypeCallAuction":        reflect.ValueOf(constant.MakeFromLiteral("1386", token.INT, 0)),
		"TypeCode":               reflect.ValueOf(constant.MakeFromLiteral("1104", token.INT, 0)),
		"TypeConnect":            reflect.ValueOf(constant.MakeFromLiteral("13", token.INT, 0)),
		"TypeCount":              reflect.ValueOf(constant.MakeFromLiteral("1102", token.INT, 0)),
		"TypeGbbq":               reflect.ValueOf(constant.MakeFromLiteral("15", token.INT, 0)),
		"TypeHeart":              reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"TypeHistoryMinute":      reflect.ValueOf(constant.MakeFromLiteral("4020", token.INT, 0)),
		"TypeHistoryMinuteTrade": reflect.ValueOf(constant.MakeFromLiteral("4021", token.INT, 0)),
		"TypeKline":              reflect.ValueOf(constant.MakeFromLiteral("1325", token.INT, 0)),
		"TypeKline15Minute":      reflect.ValueOf(protocol.TypeKline15Minute),
		"TypeKline30Minute":      reflect.ValueOf(protocol.TypeKline30Minute),
		"TypeKline5Minute":       reflect.ValueOf(protocol.TypeKline5Minute),
		"TypeKline60Minute":      reflect.ValueOf(protocol.TypeKline60Minute),
		"TypeKlineDay":           reflect.ValueOf(protocol.TypeKlineDay),
		"TypeKlineDay2":          reflect.ValueOf(protocol.TypeKlineDay2),
		"TypeKlineHour":          reflect.ValueOf(protocol.TypeKlineHour),
		"TypeKlineMinute":        reflect.ValueOf(protocol.TypeKlineMinute),
		"TypeKlineMinute2":       reflect.ValueOf(protocol.TypeKlineMinute2),
		"TypeKlineMonth":         reflect.ValueOf(protocol.TypeKlineMonth),
		"TypeKlineQuarter":       reflect.ValueOf(protocol.TypeKlineQuarter),
		"TypeKlineWeek":          reflect.ValueOf(protocol.TypeKlineWeek),
		"TypeKlineYear":          reflect.ValueOf(protocol.TypeKlineYear),
		"TypeMinute":             reflect.ValueOf(constant.MakeFromLiteral("1309", token.INT, 0)),
		"TypeMinuteTrade":        reflect.ValueOf(constant.MakeFromLiteral("4037", token.INT, 0)),
		"TypeQuote":              reflect.ValueOf(constant.MakeFromLiteral("1342", token.INT, 0)),
		"UTF8ToGBK":              reflect.ValueOf(protocol.UTF8ToGBK),
		"Uint16":                 reflect.ValueOf(protocol.Uint16),
		"Uint32":                 reflect.ValueOf(protocol.Uint32),
		"Yuan":                   reflect.ValueOf(protocol.Yuan),

		// type definitions
		"CallAuction":      reflect.ValueOf((*protocol.CallAuction)(nil)),
		"CallAuctionResp":  reflect.ValueOf((*protocol.CallAuctionResp)(nil)),
		"Code":             reflect.ValueOf((*protocol.Code)(nil)),
		"CodeResp":         reflect.ValueOf((*protocol.CodeResp)(nil)),
		"ConnectResp":      reflect.ValueOf((*protocol.ConnectResp)(nil)),
		"Control":          reflect.ValueOf((*protocol.Control)(nil)),
		"CountResp":        reflect.ValueOf((*protocol.CountResp)(nil)),
		"Equity":           reflect.ValueOf((*protocol.Equity)(nil)),
		"Exchange":         reflect.ValueOf((*protocol.Exchange)(nil)),
		"Factor":           reflect.ValueOf((*protocol.Factor)(nil)),
		"Frame":            reflect.ValueOf((*protocol.Frame)(nil)),
		"Gbbq":             reflect.ValueOf((*protocol.Gbbq)(nil)),
		"GbbqResp":         reflect.ValueOf((*protocol.GbbqResp)(nil)),
		"HistoryTradeResp": reflect.ValueOf((*protocol.HistoryTradeResp)(nil)),
		"K":                reflect.ValueOf((*protocol.K)(nil)),
		"Kline":            reflect.ValueOf((*protocol.Kline)(nil)),
		"KlineCache":       reflect.ValueOf((*protocol.KlineCache)(nil)),
		"KlineReq":         reflect.ValueOf((*protocol.KlineReq)(nil)),
		"KlineResp":        reflect.ValueOf((*protocol.KlineResp)(nil)),
		"Klines":           reflect.ValueOf((*protocol.Klines)(nil)),
		"Message":          reflect.ValueOf((*protocol.Message)(nil)),
		"MinuteResp":       reflect.ValueOf((*protocol.MinuteResp)(nil)),
		"PreKline":         reflect.ValueOf((*protocol.PreKline)(nil)),
		"PreKlines":        reflect.ValueOf((*protocol.PreKlines)(nil)),
		"Price":            reflect.ValueOf((*protocol.Price)(nil)),
		"PriceLevel":       reflect.ValueOf((*protocol.PriceLevel)(nil)),
		"PriceLevels":      reflect.ValueOf((*protocol.PriceLevels)(nil)),
		"PriceNumber":      reflect.ValueOf((*protocol.PriceNumber)(nil)),
		"Quote":            reflect.ValueOf((*protocol.Quote)(nil)),
		"QuotesResp":       reflect.ValueOf((*protocol.QuotesResp)(nil)),
		"Response":         reflect.ValueOf((*protocol.Response)(nil)),
		"Trade":            reflect.ValueOf((*protocol.Trade)(nil)),
		"TradeCache":       reflect.ValueOf((*protocol.TradeCache)(nil)),
		"TradeResp":        reflect.ValueOf((*protocol.TradeResp)(nil)),
		"Trades":           reflect.ValueOf((*protocol.Trades)(nil)),
		"XRXD":             reflect.ValueOf((*protocol.XRXD)(nil)),
		"XRXDs":            reflect.ValueOf((*protocol.XRXDs)(nil)),

		// interface wrapper definitions
		"_Message": reflect.ValueOf((*_github_com_injoyai_tdx_protocol_Message)(nil)),
	}
}

// _github_com_injoyai_tdx_protocol_Message is an interface wrapper for Message type
type _github_com_injoyai_tdx_protocol_Message struct {
	IValue interface{}
	WBytes func() types.Bytes
}

func (W _github_com_injoyai_tdx_protocol_Message) Bytes() types.Bytes {
	return W.WBytes()
}
