// Code generated by 'yaegi extract github.com/injoyai/ios/server/listen'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/server/listen"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/server/listen/listen"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Memory":       reflect.ValueOf(listen.Memory),
		"RunMemory":    reflect.ValueOf(listen.RunMemory),
		"RunTCP":       reflect.ValueOf(listen.RunTCP),
		"RunUnix":      reflect.ValueOf(listen.RunUnix),
		"RunWebsocket": reflect.ValueOf(listen.RunWebsocket),
		"TCP":          reflect.ValueOf(listen.TCP),
		"Unix":         reflect.ValueOf(listen.Unix),
		"Websocket":    reflect.ValueOf(listen.Websocket),
	}
}
