// Code generated by 'yaegi extract github.com/injoyai/ios/module/mqtt'. DO NOT EDIT.

package lib

import (
	"reflect"

	mqtt2 "github.com/eclipse/paho.mqtt.golang"
	"github.com/injoyai/ios/module/mqtt"
)

func init() {
	Symbols["github.com/injoyai/ios/module/mqtt/mqtt"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":       reflect.ValueOf(mqtt.Dial),
		"DialClient": reflect.ValueOf(mqtt.DialClient),
		"NewDial":    reflect.ValueOf(mqtt.NewDial),
		"WithBase":   reflect.ValueOf(mqtt.WithBase),

		// type definitions
		"BaseConfig": reflect.ValueOf((*mqtt.BaseConfig)(nil)),
		"Client":     reflect.ValueOf((*mqtt.Client)(nil)),
		"Config":     reflect.ValueOf((*mqtt.Config)(nil)),
		"Connect":    reflect.ValueOf((*mqtt.Connect)(nil)),
		"Message":    reflect.ValueOf((*mqtt.Message)(nil)),
		"Publish":    reflect.ValueOf((*mqtt.Publish)(nil)),
		"Subscribe":  reflect.ValueOf((*mqtt.Subscribe)(nil)),

		// interface wrapper definitions
		"_Connect": reflect.ValueOf((*_github_com_injoyai_ios_module_mqtt_Connect)(nil)),
	}
}

// _github_com_injoyai_ios_module_mqtt_Connect is an interface wrapper for Connect type
type _github_com_injoyai_ios_module_mqtt_Connect struct {
	IValue             interface{}
	WAddRoute          func(topic string, callback mqtt2.MessageHandler)
	WConnect           func() mqtt2.Token
	WDisconnect        func(quiesce uint)
	WIsConnected       func() bool
	WIsConnectionOpen  func() bool
	WOptionsReader     func() mqtt2.ClientOptionsReader
	WPublish           func(topic string, qos byte, retained bool, payload interface{}) mqtt2.Token
	WSubscribe         func(topic string, qos byte, callback mqtt2.MessageHandler) mqtt2.Token
	WSubscribeMultiple func(filters map[string]byte, callback mqtt2.MessageHandler) mqtt2.Token
	WUnsubscribe       func(topics ...string) mqtt2.Token
}

func (W _github_com_injoyai_ios_module_mqtt_Connect) AddRoute(topic string, callback mqtt2.MessageHandler) {
	W.WAddRoute(topic, callback)
}
func (W _github_com_injoyai_ios_module_mqtt_Connect) Connect() mqtt2.Token {
	return W.WConnect()
}
func (W _github_com_injoyai_ios_module_mqtt_Connect) Disconnect(quiesce uint) {
	W.WDisconnect(quiesce)
}
func (W _github_com_injoyai_ios_module_mqtt_Connect) IsConnected() bool {
	return W.WIsConnected()
}
func (W _github_com_injoyai_ios_module_mqtt_Connect) IsConnectionOpen() bool {
	return W.WIsConnectionOpen()
}
func (W _github_com_injoyai_ios_module_mqtt_Connect) OptionsReader() mqtt2.ClientOptionsReader {
	return W.WOptionsReader()
}
func (W _github_com_injoyai_ios_module_mqtt_Connect) Publish(topic string, qos byte, retained bool, payload interface{}) mqtt2.Token {
	return W.WPublish(topic, qos, retained, payload)
}
func (W _github_com_injoyai_ios_module_mqtt_Connect) Subscribe(topic string, qos byte, callback mqtt2.MessageHandler) mqtt2.Token {
	return W.WSubscribe(topic, qos, callback)
}
func (W _github_com_injoyai_ios_module_mqtt_Connect) SubscribeMultiple(filters map[string]byte, callback mqtt2.MessageHandler) mqtt2.Token {
	return W.WSubscribeMultiple(filters, callback)
}
func (W _github_com_injoyai_ios_module_mqtt_Connect) Unsubscribe(topics ...string) mqtt2.Token {
	return W.WUnsubscribe(topics...)
}
