// Code generated by 'yaegi extract github.com/injoyai/ios/client/redial'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/client/redial"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/client/redial/redial"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"MQTT":         reflect.ValueOf(redial.MQTT),
		"Memory":       reflect.ValueOf(redial.Memory),
		"Rabbitmq":     reflect.ValueOf(redial.Rabbitmq),
		"Redial":       reflect.ValueOf(redial.Redial),
		"Run":          reflect.ValueOf(redial.Run),
		"RunMQTT":      reflect.ValueOf(redial.RunMQTT),
		"RunMemory":    reflect.ValueOf(redial.RunMemory),
		"RunRabbitmq":  reflect.ValueOf(redial.RunRabbitmq),
		"RunSSH":       reflect.ValueOf(redial.RunSSH),
		"RunSerial":    reflect.ValueOf(redial.RunSerial),
		"RunTCP":       reflect.ValueOf(redial.RunTCP),
		"RunUnix":      reflect.ValueOf(redial.RunUnix),
		"RunWebsocket": reflect.ValueOf(redial.RunWebsocket),
		"SSH":          reflect.ValueOf(redial.SSH),
		"Serial":       reflect.ValueOf(redial.Serial),
		"TCP":          reflect.ValueOf(redial.TCP),
		"Unix":         reflect.ValueOf(redial.Unix),
		"Websocket":    reflect.ValueOf(redial.Websocket),
	}
}
