// Code generated by 'yaegi extract github.com/injoyai/tdx/lib/zip'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/tdx/lib/zip"

	"reflect"
)

func init() {
	Symbols["github.com/injoyai/tdx/lib/zip/zip"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Decode": reflect.ValueOf(zip.Decode),
		"Encode": reflect.ValueOf(zip.Encode),
	}
}
