// Code generated by 'yaegi extract github.com/injoyai/ios/client/dial'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/client/dial"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/client/dial/dial"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":          reflect.ValueOf(dial.Dial),
		"MQTT":          reflect.ValueOf(dial.MQTT),
		"Memory":        reflect.ValueOf(dial.Memory),
		"Rabbitmq":      reflect.ValueOf(dial.Rabbitmq),
		"Run":           reflect.ValueOf(dial.Run),
		"RunMQTT":       reflect.ValueOf(dial.RunMQTT),
		"RunMemory":     reflect.ValueOf(dial.RunMemory),
		"RunRabbitmq":   reflect.ValueOf(dial.RunRabbitmq),
		"RunSSH":        reflect.ValueOf(dial.RunSSH),
		"RunSerial":     reflect.ValueOf(dial.RunSerial),
		"RunTCP":        reflect.ValueOf(dial.RunTCP),
		"RunUnix":       reflect.ValueOf(dial.RunUnix),
		"RunWebsocket":  reflect.ValueOf(dial.RunWebsocket),
		"SSH":           reflect.ValueOf(dial.SSH),
		"Serial":        reflect.ValueOf(dial.Serial),
		"TCP":           reflect.ValueOf(dial.TCP),
		"Unix":          reflect.ValueOf(dial.Unix),
		"Websocket":     reflect.ValueOf(dial.Websocket),
		"WithMQTT":      reflect.ValueOf(&dial.WithMQTT).Elem(),
		"WithMemory":    reflect.ValueOf(&dial.WithMemory).Elem(),
		"WithRabbitmq":  reflect.ValueOf(&dial.WithRabbitmq).Elem(),
		"WithSSH":       reflect.ValueOf(&dial.WithSSH).Elem(),
		"WithSerial":    reflect.ValueOf(&dial.WithSerial).Elem(),
		"WithTCP":       reflect.ValueOf(&dial.WithTCP).Elem(),
		"WithUnix":      reflect.ValueOf(&dial.WithUnix).Elem(),
		"WithWebsocket": reflect.ValueOf(&dial.WithWebsocket).Elem(),
	}
}
