// Code generated by 'yaegi extract github.com/injoyai/tdx/extend'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/tdx/extend"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/tdx/extend/extend"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AllKlineType":                  reflect.ValueOf(&extend.AllKlineType).Elem(),
		"AllTable":                      reflect.ValueOf(&extend.AllTable).Elem(),
		"Day":                           reflect.ValueOf(constant.MakeFromLiteral("\"day\"", token.STRING, 0)),
		"DefaultDayKlineExportTitle":    reflect.ValueOf(&extend.DefaultDayKlineExportTitle).Elem(),
		"DefaultMinuteKlineExportTitle": reflect.ValueOf(&extend.DefaultMinuteKlineExportTitle).Elem(),
		"DialCodesHTTP":                 reflect.ValueOf(extend.DialCodesHTTP),
		"DialGbbqHTTP":                  reflect.ValueOf(extend.DialGbbqHTTP),
		"DoIncomes":                     reflect.ValueOf(extend.DoIncomes),
		"GetBjCodes":                    reflect.ValueOf(extend.GetBjCodes),
		"GetSinaFactor":                 reflect.ValueOf(extend.GetSinaFactor),
		"GetSinaFactorFull":             reflect.ValueOf(extend.GetSinaFactorFull),
		"GetTHSDayKline":                reflect.ValueOf(extend.GetTHSDayKline),
		"GetTHSDayKlineFactorFull":      reflect.ValueOf(extend.GetTHSDayKlineFactorFull),
		"GetTHSDayKlineFull":            reflect.ValueOf(extend.GetTHSDayKlineFull),
		"KlineTableMap":                 reflect.ValueOf(&extend.KlineTableMap).Elem(),
		"KlinesToCsv":                   reflect.ValueOf(extend.KlinesToCsv),
		"ListenCodesAndGbbqHTTP":        reflect.ValueOf(extend.ListenCodesAndGbbqHTTP),
		"ListenCodesHTTP":               reflect.ValueOf(extend.ListenCodesHTTP),
		"Minute":                        reflect.ValueOf(constant.MakeFromLiteral("\"minute\"", token.STRING, 0)),
		"Minute15":                      reflect.ValueOf(constant.MakeFromLiteral("\"15minute\"", token.STRING, 0)),
		"Minute30":                      reflect.ValueOf(constant.MakeFromLiteral("\"30minute\"", token.STRING, 0)),
		"Minute5":                       reflect.ValueOf(constant.MakeFromLiteral("\"5minute\"", token.STRING, 0)),
		"Minute60":                      reflect.ValueOf(constant.MakeFromLiteral("\"60minute\"", token.STRING, 0)),
		"Month":                         reflect.ValueOf(constant.MakeFromLiteral("\"month\"", token.STRING, 0)),
		"NewKlineTable":                 reflect.ValueOf(extend.NewKlineTable),
		"NewPullKline":                  reflect.ValueOf(extend.NewPullKline),
		"NewPullTrade":                  reflect.ValueOf(extend.NewPullTrade),
		"Quarter":                       reflect.ValueOf(constant.MakeFromLiteral("\"quarter\"", token.STRING, 0)),
		"Sina_HFQ":                      reflect.ValueOf(constant.MakeFromLiteral("\"hfq\"", token.STRING, 0)),
		"Sina_QFQ":                      reflect.ValueOf(constant.MakeFromLiteral("\"qfq\"", token.STRING, 0)),
		"THS_BFQ":                       reflect.ValueOf(extend.THS_BFQ),
		"THS_HFQ":                       reflect.ValueOf(extend.THS_HFQ),
		"THS_QFQ":                       reflect.ValueOf(extend.THS_QFQ),
		"Table15Minute":                 reflect.ValueOf(constant.MakeFromLiteral("\"Minute15Kline\"", token.STRING, 0)),
		"Table30Minute":                 reflect.ValueOf(constant.MakeFromLiteral("\"Minute30Kline\"", token.STRING, 0)),
		"Table5Minute":                  reflect.ValueOf(constant.MakeFromLiteral("\"Minute5Kline\"", token.STRING, 0)),
		"Table60Minute":                 reflect.ValueOf(constant.MakeFromLiteral("\"Minute60Kline\"", token.STRING, 0)),
		"TableDay":                      reflect.ValueOf(constant.MakeFromLiteral("\"DayKline\"", token.STRING, 0)),
		"TableMinute":                   reflect.ValueOf(constant.MakeFromLiteral("\"MinuteKline\"", token.STRING, 0)),
		"TableMonth":                    reflect.ValueOf(constant.MakeFromLiteral("\"MonthKline\"", token.STRING, 0)),
		"TableQuarter":                  reflect.ValueOf(constant.MakeFromLiteral("\"QuarterKline\"", token.STRING, 0)),
		"TableWeek":                     reflect.ValueOf(constant.MakeFromLiteral("\"WeekKline\"", token.STRING, 0)),
		"TableYear":                     reflect.ValueOf(constant.MakeFromLiteral("\"YearKline\"", token.STRING, 0)),
		"TradeToCsv":                    reflect.ValueOf(extend.TradeToCsv),
		"UrlSinaFactorHfq":              reflect.ValueOf(constant.MakeFromLiteral("\"https://finance.sina.com.cn/realstock/company/%s/hfq.js\"", token.STRING, 0)),
		"UrlSinaFactorQfq":              reflect.ValueOf(constant.MakeFromLiteral("\"https://finance.sina.com.cn/realstock/company/%s/qfq.js\"", token.STRING, 0)),
		"UrlTHSDayKline":                reflect.ValueOf(constant.MakeFromLiteral("\"http://d.10jqka.com.cn/v6/line/hs_%s/0%d/all.js\"", token.STRING, 0)),
		"Week":                          reflect.ValueOf(constant.MakeFromLiteral("\"week\"", token.STRING, 0)),
		"Year":                          reflect.ValueOf(constant.MakeFromLiteral("\"year\"", token.STRING, 0)),

		// type definitions
		"CodesHTTP":       reflect.ValueOf((*extend.CodesHTTP)(nil)),
		"Factor":          reflect.ValueOf((*extend.Factor)(nil)),
		"Factors":         reflect.ValueOf((*extend.Factors)(nil)),
		"GbbqHTTP":        reflect.ValueOf((*extend.GbbqHTTP)(nil)),
		"Income":          reflect.ValueOf((*extend.Income)(nil)),
		"Incomes":         reflect.ValueOf((*extend.Incomes)(nil)),
		"Info":            reflect.ValueOf((*extend.Info)(nil)),
		"Kline":           reflect.ValueOf((*extend.Kline)(nil)),
		"KlineHandler":    reflect.ValueOf((*extend.KlineHandler)(nil)),
		"KlineTable":      reflect.ValueOf((*extend.KlineTable)(nil)),
		"Klines":          reflect.ValueOf((*extend.Klines)(nil)),
		"PullKline":       reflect.ValueOf((*extend.PullKline)(nil)),
		"PullKlineConfig": reflect.ValueOf((*extend.PullKlineConfig)(nil)),
		"PullTrade":       reflect.ValueOf((*extend.PullTrade)(nil)),
	}
}
