// Code generated by 'yaegi extract github.com/injoyai/tdx/lib/bse'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/tdx/lib/bse"

	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/tdx/lib/bse/bse"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"GetCodes": reflect.ValueOf(bse.GetCodes),
		"UrlCodes": reflect.ValueOf(constant.MakeFromLiteral("\"https://www.bse.cn/nqhqController/nqhq_en.do?callback=jQuery3710848510589806625_%d\"", token.STRING, 0)),

		// type definitions
		"Code":  reflect.ValueOf((*bse.Code)(nil)),
		"Codes": reflect.ValueOf((*bse.Codes)(nil)),
	}
}
