// Code generated by 'yaegi extract github.com/injoyai/tdx/lib/xorms'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/tdx/lib/xorms"

	"reflect"
)

func init() {
	Symbols["github.com/injoyai/tdx/lib/xorms/xorms"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"New":                 reflect.ValueOf(xorms.New),
		"NewMysql":            reflect.ValueOf(xorms.NewMysql),
		"NewSessionFunc":      reflect.ValueOf(xorms.NewSessionFunc),
		"NewSqlite":           reflect.ValueOf(xorms.NewSqlite),
		"WithCfg":             reflect.ValueOf(xorms.WithCfg),
		"WithConnMaxLifetime": reflect.ValueOf(xorms.WithConnMaxLifetime),
		"WithDMap":            reflect.ValueOf(xorms.WithDMap),
		"WithMaxIdleConns":    reflect.ValueOf(xorms.WithMaxIdleConns),
		"WithMaxOpenConns":    reflect.ValueOf(xorms.WithMaxOpenConns),
		"WithSyncField":       reflect.ValueOf(xorms.WithSyncField),
		"WithTablePrefix":     reflect.ValueOf(xorms.WithTablePrefix),

		// type definitions
		"Engine":  reflect.ValueOf((*xorms.Engine)(nil)),
		"Option":  reflect.ValueOf((*xorms.Option)(nil)),
		"Session": reflect.ValueOf((*xorms.Session)(nil)),
	}
}
