// Code generated by 'yaegi extract github.com/injoyai/ios/client/frame/v2'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/client/frame/v2"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/client/frame/v2/frame"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Default":   reflect.ValueOf(&frame.Default).Elem(),
		"Fail":      reflect.ValueOf(&frame.Fail).Elem(),
		"OnMessage": reflect.ValueOf(frame.OnMessage),
		"Prefix":    reflect.ValueOf(&frame.Prefix).Elem(),
		"ReadFrom":  reflect.ValueOf(frame.ReadFrom),
		"Succ":      reflect.ValueOf(&frame.Succ).Elem(),
		"WriteWith": reflect.ValueOf(frame.WriteWith),

		// type definitions
		"Frame": reflect.ValueOf((*frame.Frame)(nil)),
		"Model": reflect.ValueOf((*frame.Model)(nil)),
	}
}
