// Code generated by 'yaegi extract github.com/injoyai/ios/module/serial'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/module/serial"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/module/serial/serial"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Dial":    reflect.ValueOf(serial.Dial),
		"NewDial": reflect.ValueOf(serial.NewDial),

		// type definitions
		"Client": reflect.ValueOf((*serial.Client)(nil)),
		"Config": reflect.ValueOf((*serial.Config)(nil)),
	}
}
