// Code generated by 'yaegi extract github.com/injoyai/ios/module/tcp'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/ios/module/tcp"
	"reflect"
)

func init() {
	Symbols["github.com/injoyai/ios/module/tcp/tcp"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NewDial":   reflect.ValueOf(tcp.NewDial),
		"NewListen": reflect.ValueOf(tcp.NewListen),

		// type definitions
		"Server": reflect.ValueOf((*tcp.Server)(nil)),
	}
}
