// Code generated by 'yaegi extract github.com/injoyai/tdx'. DO NOT EDIT.

package lib

import (
	"github.com/injoyai/tdx"
	"github.com/injoyai/tdx/protocol"
	"go/constant"
	"go/token"
	"iter"
	"reflect"
	"time"
)

func init() {
	Symbols["github.com/injoyai/tdx/tdx"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BJHosts":               reflect.ValueOf(&tdx.BJHosts).Elem(),
		"DefaultClients":        reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"DefaultCodes":          reflect.ValueOf(&tdx.DefaultCodes).Elem(),
		"DefaultCodesSpec":      reflect.ValueOf(constant.MakeFromLiteral("\"0 1 9 * * *\"", token.STRING, 0)),
		"DefaultDataDir":        reflect.ValueOf(constant.MakeFromLiteral("\"./data\"", token.STRING, 0)),
		"DefaultDatabaseDir":    reflect.ValueOf(constant.MakeFromLiteral("\"./data/database\"", token.STRING, 0)),
		"DefaultGbbqSpec":       reflect.ValueOf(constant.MakeFromLiteral("\"0 5 9 * * *\"", token.STRING, 0)),
		"DefaultRetry":          reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"DefaultWorkdaySpec":    reflect.ValueOf(constant.MakeFromLiteral("\"0 3 9 * * *\"", token.STRING, 0)),
		"Dial":                  reflect.ValueOf(tdx.Dial),
		"DialDefault":           reflect.ValueOf(tdx.DialDefault),
		"DialHosts":             reflect.ValueOf(tdx.DialHosts),
		"DialHostsRandom":       reflect.ValueOf(tdx.DialHostsRandom),
		"DialHostsRange":        reflect.ValueOf(tdx.DialHostsRange),
		"DialWith":              reflect.ValueOf(tdx.DialWith),
		"FastHosts":             reflect.ValueOf(tdx.FastHosts),
		"GZHosts":               reflect.ValueOf(&tdx.GZHosts).Elem(),
		"Hosts":                 reflect.ValueOf(&tdx.Hosts).Elem(),
		"IntegerDay":            reflect.ValueOf(tdx.IntegerDay),
		"LevelAll":              reflect.ValueOf(constant.MakeFromLiteral("999", token.INT, 0)),
		"LevelDebug":            reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"LevelError":            reflect.ValueOf(constant.MakeFromLiteral("7", token.INT, 0)),
		"LevelInfo":             reflect.ValueOf(constant.MakeFromLiteral("5", token.INT, 0)),
		"LevelNone":             reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"LevelRead":             reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"LevelWrite":            reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"NewCodes":              reflect.ValueOf(tdx.NewCodes),
		"NewCodesBase":          reflect.ValueOf(tdx.NewCodesBase),
		"NewCodesMysql":         reflect.ValueOf(tdx.NewCodesMysql),
		"NewCodesSqlite":        reflect.ValueOf(tdx.NewCodesSqlite),
		"NewGbbq":               reflect.ValueOf(tdx.NewGbbq),
		"NewHostDial":           reflect.ValueOf(tdx.NewHostDial),
		"NewManage":             reflect.ValueOf(tdx.NewManage),
		"NewManageMysql":        reflect.ValueOf(tdx.NewManageMysql),
		"NewPool":               reflect.ValueOf(tdx.NewPool),
		"NewRandomDial":         reflect.ValueOf(tdx.NewRandomDial),
		"NewRangeDial":          reflect.ValueOf(tdx.NewRangeDial),
		"NewTCPDial":            reflect.ValueOf(tdx.NewTCPDial),
		"NewTimer":              reflect.ValueOf(tdx.NewTimer),
		"NewUpdated":            reflect.ValueOf(tdx.NewUpdated),
		"NewWorkday":            reflect.ValueOf(tdx.NewWorkday),
		"NewWorkdayMysql":       reflect.ValueOf(tdx.NewWorkdayMysql),
		"NewWorkdaySqlite":      reflect.ValueOf(tdx.NewWorkdaySqlite),
		"SHHosts":               reflect.ValueOf(&tdx.SHHosts).Elem(),
		"WHHosts":               reflect.ValueOf(&tdx.WHHosts).Elem(),
		"WithClients":           reflect.ValueOf(tdx.WithClients),
		"WithCodes":             reflect.ValueOf(tdx.WithCodes),
		"WithCodesClient":       reflect.ValueOf(tdx.WithCodesClient),
		"WithCodesDB":           reflect.ValueOf(tdx.WithCodesDB),
		"WithCodesDialClient":   reflect.ValueOf(tdx.WithCodesDialClient),
		"WithCodesDialDB":       reflect.ValueOf(tdx.WithCodesDialDB),
		"WithCodesOption":       reflect.ValueOf(tdx.WithCodesOption),
		"WithCodesRetry":        reflect.ValueOf(tdx.WithCodesRetry),
		"WithCodesSpec":         reflect.ValueOf(tdx.WithCodesSpec),
		"WithDebug":             reflect.ValueOf(tdx.WithDebug),
		"WithDialCodes":         reflect.ValueOf(tdx.WithDialCodes),
		"WithDialGbbq":          reflect.ValueOf(tdx.WithDialGbbq),
		"WithDialGbbqDefault":   reflect.ValueOf(tdx.WithDialGbbqDefault),
		"WithDialPool":          reflect.ValueOf(tdx.WithDialPool),
		"WithDialWorkday":       reflect.ValueOf(tdx.WithDialWorkday),
		"WithGbbq":              reflect.ValueOf(tdx.WithGbbq),
		"WithGbbqClient":        reflect.ValueOf(tdx.WithGbbqClient),
		"WithGbbqDB":            reflect.ValueOf(tdx.WithGbbqDB),
		"WithGbbqDialClient":    reflect.ValueOf(tdx.WithGbbqDialClient),
		"WithGbbqDialDB":        reflect.ValueOf(tdx.WithGbbqDialDB),
		"WithGbbqOption":        reflect.ValueOf(tdx.WithGbbqOption),
		"WithGbbqRetry":         reflect.ValueOf(tdx.WithGbbqRetry),
		"WithGbbqSpec":          reflect.ValueOf(tdx.WithGbbqSpec),
		"WithLevel":             reflect.ValueOf(tdx.WithLevel),
		"WithOption":            reflect.ValueOf(tdx.WithOption),
		"WithPool":              reflect.ValueOf(tdx.WithPool),
		"WithRedial":            reflect.ValueOf(tdx.WithRedial),
		"WithWorkday":           reflect.ValueOf(tdx.WithWorkday),
		"WithWorkdayClient":     reflect.ValueOf(tdx.WithWorkdayClient),
		"WithWorkdayDB":         reflect.ValueOf(tdx.WithWorkdayDB),
		"WithWorkdayDialClient": reflect.ValueOf(tdx.WithWorkdayDialClient),
		"WithWorkdayDialDB":     reflect.ValueOf(tdx.WithWorkdayDialDB),
		"WithWorkdayOption":     reflect.ValueOf(tdx.WithWorkdayOption),
		"WithWorkdayRetry":      reflect.ValueOf(tdx.WithWorkdayRetry),
		"WithWorkdaySpec":       reflect.ValueOf(tdx.WithWorkdaySpec),

		// type definitions
		"Client":          reflect.ValueOf((*tdx.Client)(nil)),
		"CodeModel":       reflect.ValueOf((*tdx.CodeModel)(nil)),
		"CodeModels":      reflect.ValueOf((*tdx.CodeModels)(nil)),
		"Codes":           reflect.ValueOf((*tdx.Codes)(nil)),
		"CodesBase":       reflect.ValueOf((*tdx.CodesBase)(nil)),
		"CodesOption":     reflect.ValueOf((*tdx.CodesOption)(nil)),
		"DialClientFunc":  reflect.ValueOf((*tdx.DialClientFunc)(nil)),
		"DialCodesFunc":   reflect.ValueOf((*tdx.DialCodesFunc)(nil)),
		"DialDBFunc":      reflect.ValueOf((*tdx.DialDBFunc)(nil)),
		"DialGbbqFunc":    reflect.ValueOf((*tdx.DialGbbqFunc)(nil)),
		"DialPoolFunc":    reflect.ValueOf((*tdx.DialPoolFunc)(nil)),
		"DialResult":      reflect.ValueOf((*tdx.DialResult)(nil)),
		"DialWorkdayFunc": reflect.ValueOf((*tdx.DialWorkdayFunc)(nil)),
		"Gbbq":            reflect.ValueOf((*tdx.Gbbq)(nil)),
		"GbbqOption":      reflect.ValueOf((*tdx.GbbqOption)(nil)),
		"ICodes":          reflect.ValueOf((*tdx.ICodes)(nil)),
		"IGbbq":           reflect.ValueOf((*tdx.IGbbq)(nil)),
		"IPool":           reflect.ValueOf((*tdx.IPool)(nil)),
		"Manage":          reflect.ValueOf((*tdx.Manage)(nil)),
		"Option":          reflect.ValueOf((*tdx.Option)(nil)),
		"Pool":            reflect.ValueOf((*tdx.Pool)(nil)),
		"UpdateModel":     reflect.ValueOf((*tdx.UpdateModel)(nil)),
		"Updated":         reflect.ValueOf((*tdx.Updated)(nil)),
		"Updater":         reflect.ValueOf((*tdx.Updater)(nil)),
		"Workday":         reflect.ValueOf((*tdx.Workday)(nil)),
		"WorkdayModel":    reflect.ValueOf((*tdx.WorkdayModel)(nil)),
		"WorkdayOption":   reflect.ValueOf((*tdx.WorkdayOption)(nil)),

		// interface wrapper definitions
		"_ICodes":  reflect.ValueOf((*_github_com_injoyai_tdx_ICodes)(nil)),
		"_IGbbq":   reflect.ValueOf((*_github_com_injoyai_tdx_IGbbq)(nil)),
		"_IPool":   reflect.ValueOf((*_github_com_injoyai_tdx_IPool)(nil)),
		"_Updater": reflect.ValueOf((*_github_com_injoyai_tdx_Updater)(nil)),
	}
}

// _github_com_injoyai_tdx_ICodes is an interface wrapper for ICodes type
type _github_com_injoyai_tdx_ICodes struct {
	IValue         interface{}
	WGet           func(code string) *tdx.CodeModel
	WGetETFCodes   func(limit ...int) []string
	WGetETFs       func(limit ...int) tdx.CodeModels
	WGetIndexCodes func(limit ...int) []string
	WGetIndexes    func(limit ...int) tdx.CodeModels
	WGetName       func(code string) string
	WGetStockCodes func(limit ...int) []string
	WGetStocks     func(limit ...int) tdx.CodeModels
	WIter          func() iter.Seq2[string, *tdx.CodeModel]
}

func (W _github_com_injoyai_tdx_ICodes) Get(code string) *tdx.CodeModel {
	return W.WGet(code)
}
func (W _github_com_injoyai_tdx_ICodes) GetETFCodes(limit ...int) []string {
	return W.WGetETFCodes(limit...)
}
func (W _github_com_injoyai_tdx_ICodes) GetETFs(limit ...int) tdx.CodeModels {
	return W.WGetETFs(limit...)
}
func (W _github_com_injoyai_tdx_ICodes) GetIndexCodes(limit ...int) []string {
	return W.WGetIndexCodes(limit...)
}
func (W _github_com_injoyai_tdx_ICodes) GetIndexes(limit ...int) tdx.CodeModels {
	return W.WGetIndexes(limit...)
}
func (W _github_com_injoyai_tdx_ICodes) GetName(code string) string {
	return W.WGetName(code)
}
func (W _github_com_injoyai_tdx_ICodes) GetStockCodes(limit ...int) []string {
	return W.WGetStockCodes(limit...)
}
func (W _github_com_injoyai_tdx_ICodes) GetStocks(limit ...int) tdx.CodeModels {
	return W.WGetStocks(limit...)
}
func (W _github_com_injoyai_tdx_ICodes) Iter() iter.Seq2[string, *tdx.CodeModel] {
	return W.WIter()
}

// _github_com_injoyai_tdx_IGbbq is an interface wrapper for IGbbq type
type _github_com_injoyai_tdx_IGbbq struct {
	IValue       interface{}
	WGetEquity   func(code string, t time.Time) *protocol.Equity
	WGetFactors  func(code string, ks protocol.Klines) []*protocol.Factor
	WGetTurnover func(code string, t time.Time, volume int64) float64
	WGetXRXDs    func(code string) protocol.XRXDs
}

func (W _github_com_injoyai_tdx_IGbbq) GetEquity(code string, t time.Time) *protocol.Equity {
	return W.WGetEquity(code, t)
}
func (W _github_com_injoyai_tdx_IGbbq) GetFactors(code string, ks protocol.Klines) []*protocol.Factor {
	return W.WGetFactors(code, ks)
}
func (W _github_com_injoyai_tdx_IGbbq) GetTurnover(code string, t time.Time, volume int64) float64 {
	return W.WGetTurnover(code, t, volume)
}
func (W _github_com_injoyai_tdx_IGbbq) GetXRXDs(code string) protocol.XRXDs {
	return W.WGetXRXDs(code)
}

// _github_com_injoyai_tdx_IPool is an interface wrapper for IPool type
type _github_com_injoyai_tdx_IPool struct {
	IValue interface{}
	WDo    func(fn func(c *tdx.Client) error) error
	WGet   func() (*tdx.Client, error)
	WGo    func(fn func(c *tdx.Client)) error
	WPut   func(c *tdx.Client)
}

func (W _github_com_injoyai_tdx_IPool) Do(fn func(c *tdx.Client) error) error {
	return W.WDo(fn)
}
func (W _github_com_injoyai_tdx_IPool) Get() (*tdx.Client, error) {
	return W.WGet()
}
func (W _github_com_injoyai_tdx_IPool) Go(fn func(c *tdx.Client)) error {
	return W.WGo(fn)
}
func (W _github_com_injoyai_tdx_IPool) Put(c *tdx.Client) {
	W.WPut(c)
}

// _github_com_injoyai_tdx_Updater is an interface wrapper for Updater type
type _github_com_injoyai_tdx_Updater struct {
	IValue  interface{}
	WUpdate func() error
}

func (W _github_com_injoyai_tdx_Updater) Update() error {
	return W.WUpdate()
}
