package domain

import (
	"encoding/json"
	"time"
)

// M0-06 data domain types. These mirror the OpenAPI schemas
// (docs/api/openapi.json, generated by docs/api/build_openapi.py) so the wire
// DTO mapping is direct. The contracts.go draft uses slightly different
// casing; OpenAPI is the authoritative HTTP contract, so field names follow
// it and Go identifiers follow the project's MixedCase convention.

// Page is the cursor pagination input shared by list APIs and provider fetch.
// Cursor is opaque to callers; limit is bounded per endpoint.
type Page struct {
	Cursor string
	Limit  int
}

// PageResult is one page of items plus the opaque resume point. NextCursor
// is empty when the page ended the collection.
type PageResult[T any] struct {
	Items      []T
	NextCursor string
}

// FieldType enumerates the scalar types a dataset field may carry. The wire
// values match the OpenAPI Field.type enum; Decimal is a JSON string so no
// precision is lost crossing HTTP.
type FieldType string

const (
	FieldDecimal   FieldType = "decimal"
	FieldNumber    FieldType = "number"
	FieldString    FieldType = "string"
	FieldBoolean   FieldType = "boolean"
	FieldTimestamp FieldType = "timestamp"
)

// Field describes one column of a dataset schema. Unit is mandatory even for
// dimensionless fields ("count", "ratio", "currency:USD") so downstream
// consumers never guess what a number means.
type Field struct {
	Name        string    `json:"name"`
	Type        FieldType `json:"type"`
	Unit        string    `json:"unit"`
	Nullable    bool      `json:"nullable"`
	Description string    `json:"description,omitempty"`
}

// PITLevel declares how strongly a dataset's point-in-time evidence is
// verified. Verified means the provider publishes real available_at; date_only
// means only a calendar date is known (a conservative policy must be picked);
// unverified means revisions may be silently backfilled.
type PITLevel string

const (
	PITVerified   PITLevel = "verified"
	PITDateOnly   PITLevel = "date_only"
	PITUnverified PITLevel = "unverified"
)

// Capability is one dataset a provider can serve through a connection. A
// provider that does not support a dataset must say so explicitly; it never
// silently substitutes another dataset or frequency.
type Capability struct {
	Dataset     string    `json:"dataset"`
	Fields      []Field   `json:"fields"`
	Frequencies []string  `json:"frequencies"`
	Coverage    *Interval `json:"coverage"`
	PITLevel    PITLevel  `json:"pit_level"`
	MaxPageSize int       `json:"max_page_size"`
}

// ProviderDescriptor is what Describe returns: the provider's own versioned
// identity, its JSON Schema for connection settings, and the datasets it can
// serve. Settings schema is JSON Schema 2020-12, validated by the provider
// factory before Open; the server never persists arbitrary settings.
type ProviderDescriptor struct {
	Ref          VersionRef   `json:"id"` // OpenAPI flattens id+version; ref carries both.
	Name         string       `json:"name"`
	ConfigSchema any          `json:"config_schema"`
	Capabilities []Capability `json:"capabilities"`
}

// ConnectionConfig is the bound, versioned connection a DataProvider is opened
// against. Settings is the validated JSON the provider's schema accepted;
// SecretRef is an opaque pointer into the secret store, never a plaintext
// value. ParentID chains versions of the same logical connection.
type ConnectionConfig struct {
	Ref       VersionRef      `json:"-"` // not on the wire; set by the server.
	Provider  VersionRef      `json:"provider_ref"`
	Name      string          `json:"name"`
	Settings  json.RawMessage `json:"settings"`
	SecretRef string          `json:"secret_ref,omitempty"`
	ParentID  string          `json:"parent_id,omitempty"`
}

// FetchRequest is the input to DataProvider.Fetch. Range is half-open
// [From, To); instrument_ids is non-empty; fields selects the columns to
// return. Page carries the provider's own cursor (separate from the API's
// snapshot-bound cursor).
type FetchRequest struct {
	Dataset       string   `json:"dataset"`
	Frequency     string   `json:"frequency"`
	InstrumentIDs []ID     `json:"instrument_ids"`
	Fields        []string `json:"fields"`
	Range         Interval `json:"range"`
	Page          Page     `json:"-"`
}

// RawPage is one bounded page of upstream content. Payload is the provider's
// native encoding (CSV, JSON, Arrow, ...); the normalizer is the only
// consumer. NextCursor is the provider's resume point; Checksum is the
// SHA-256 of Payload so the same content is detectable across fetches.
// ProviderRevision identifies the upstream revision the page came from, so
// revisions are tracked even when content is byte-identical.
type RawPage struct {
	Payload          []byte    `json:"-"`
	ContentType      string    `json:"-"`
	NextCursor       string    `json:"-"`
	ProviderRevision string    `json:"-"`
	Checksum         string    `json:"-"`
	FetchedAt        time.Time `json:"-"`
}

// Provenance ties one Observation to its source evidence. Each field maps to
// the OpenAPI Provenance schema; AvailableAt is the decision-time-relevant
// "first research-usable" timestamp, never replaced by ingested_at. A nil
// PublishedAt means the upstream did not announce a publish time; the
// availability policy must then choose a conservative value, never the
// event time itself.
type Provenance struct {
	SourceID             ID         `json:"source_id"`
	SourceRecordID       string     `json:"source_record_id"`
	RevisionID           string     `json:"revision_id"`
	SupersedesRevisionID string     `json:"supersedes_revision_id,omitempty"`
	PublishedAt          *time.Time `json:"published_at,omitempty"`
	AvailableAt          time.Time  `json:"available_at"`
	IngestedAt           time.Time  `json:"ingested_at"`
	SchemaVersion        string     `json:"schema_version"`
	PolicyVersion        string     `json:"policy_version"`
	QualityFlags         []string   `json:"quality_flags"`
}

// ValueKind matches the OpenAPI Value.kind enum. Decimal is a string on the
// wire; number is a JSON number for statistics only.
type ValueKind string

const (
	ValueDecimal   ValueKind = "decimal"
	ValueNumber    ValueKind = "number"
	ValueString    ValueKind = "string"
	ValueBoolean   ValueKind = "boolean"
	ValueTimestamp ValueKind = "timestamp"
)

// Value is one scalar cell. MissingReason is the only allowed companion to a
// null value; absent reason with a null value is a schema violation. Encoded
// holds the canonical scalar form (decimal plain notation, RFC3339 timestamp,
// etc.); callers must not infer kind from Encoded's text shape.
type Value struct {
	Kind          ValueKind `json:"kind"`
	Encoded       string    `json:"value,omitempty"`
	MissingReason string    `json:"missing_reason,omitempty"`
}

// Observation is one normalized row: a point-in-time measurement of one
// instrument (or entity) on one dataset at one event time. Effective is the
// half-open interval during which the value is the authoritative revision;
// nil means "no later revision superseded this in the snapshot" and the
// normalizer should still set it to [event_time, +inf) when persisting.
// PeriodEnd is the economic period end (financial reporting date); it is not
// a substitute for available_at.
type Observation struct {
	InstrumentID *ID              `json:"instrument_id,omitempty"`
	EntityID     *ID              `json:"entity_id,omitempty"`
	Dataset      string           `json:"dataset"`
	EventTime    time.Time        `json:"event_time"`
	PeriodEnd    *string          `json:"period_end,omitempty"`
	Effective    *Interval        `json:"effective,omitempty"`
	Values       map[string]Value `json:"values"`
	Provenance   Provenance       `json:"provenance"`
}

// IngestMode controls how a fetch treats the upstream cache. Incremental
// resumes from the last cursor; backfill fetches a stated range; force always
// calls the upstream even when the cache is current, and records the new
// request as evidence (contract rule).
type IngestMode string

const (
	IngestIncremental IngestMode = "incremental"
	IngestBackfill    IngestMode = "backfill"
	IngestForce       IngestMode = "force"
)

// IngestReceipt is the result of appending observations: the batch they were
// persisted under, the row count and the quality issues found. Issues never
// silently block publishing; the caller (snapshot decision) decides.
type IngestReceipt struct {
	BatchID ID      `json:"batch_id"`
	Rows    int64   `json:"row_count"`
	Issues  []Issue `json:"issues"`
}

// Batch is the wire-visible record of one ingest unit (OpenAPI Batch
// schema): the batch a set of observations was persisted under, its
// content-addressed checksum and the quality issues the pipeline attached.
// Ready reports whether the batch may be frozen into a snapshot; severity
// gating happens at publish time, never silently at append time.
type Batch struct {
	ID        ID        `json:"id"`
	JobID     ID        `json:"job_id"`
	DatasetID string    `json:"dataset_id"`
	RowCount  int64     `json:"row_count"`
	Checksum  string    `json:"checksum"`
	CreatedAt time.Time `json:"created_at"`
	Issues    []Issue   `json:"issues"`
	Ready     bool      `json:"ready"`
}

// SnapshotRequest is the input to PublishSnapshot: a name, the batches to
// freeze, and whether strict PIT mode rejects unverified available_at
// evidence. At least one batch is required.
type SnapshotRequest struct {
	Name      string `json:"name"`
	BatchIDs  []ID   `json:"batch_ids"`
	StrictPIT bool   `json:"strict_pit"`
}

// Snapshot is the immutable, content-addressed view over a set of batches.
// ManifestHash is the SHA-256 of the canonical manifest — the member batch
// ids with their checksums plus the strict-PIT policy — so the same batch
// set and policy always hash identically; once published, the snapshot is
// never modified.
type Snapshot struct {
	ID            ID        `json:"id"`
	Name          string    `json:"name"`
	BatchIDs      []ID      `json:"batch_ids"`
	StrictPIT     bool      `json:"strict_pit"`
	ManifestHash  string    `json:"manifest_hash"`
	CreatedAt     time.Time `json:"created_at"`
	QualityIssues []Issue   `json:"quality_issues"`
}

// DataQuery is the point-in-time read input: bound to a snapshot and an as_of
// decision time. InstrumentIDs and Fields are non-empty; Range is half-open;
// Cursor is the API's own (snapshot-bound) cursor, distinct from provider
// cursors. Limit is bounded by the data row endpoint (max 1000). ReplayTime
// optionally narrows visibility to rows ingested at or before that wall-clock
// moment, for replay runs that must not observe late arrivals.
type DataQuery struct {
	SnapshotID    ID         `json:"snapshot_id"`
	AsOf          time.Time  `json:"as_of"`
	ReplayTime    *time.Time `json:"replay_time,omitempty"`
	Dataset       string     `json:"dataset"`
	Frequency     string     `json:"frequency"`
	InstrumentIDs []ID       `json:"instrument_ids"`
	Fields        []string   `json:"fields"`
	Range         Interval   `json:"range"`
	Cursor        string     `json:"cursor,omitempty"`
	Limit         int        `json:"limit,omitempty"`
}

// ValidateFetch checks the contract a provider's Fetch caller must uphold
// before invoking the adapter. It fails closed: empty dataset, empty
// instruments, zero-length or inverted range, and unknown fields are all
// rejected rather than passed to the provider.
func (r FetchRequest) Validate() error {
	if r.Dataset == "" {
		return NewError(CodeValidationInvalid, "fetch: dataset is required")
	}
	if r.Frequency == "" {
		return NewError(CodeValidationInvalid, "fetch: frequency is required")
	}
	if len(r.InstrumentIDs) == 0 {
		return NewError(CodeValidationInvalid, "fetch: instrument_ids is required")
	}
	for i, id := range r.InstrumentIDs {
		if id == "" {
			return NewError(CodeValidationInvalid, "fetch: instrument_ids[%d] is empty", i)
		}
	}
	if _, err := NewInterval(r.Range.From, r.Range.To); err != nil {
		return Wrap(err, CodeValidationInterval, "fetch: range invalid")
	}
	if len(r.Fields) == 0 {
		return NewError(CodeValidationInvalid, "fetch: fields is required")
	}
	return nil
}

// Validate checks the snapshot publish contract: name and at least one batch.
func (r SnapshotRequest) Validate() error {
	if r.Name == "" {
		return NewError(CodeValidationInvalid, "snapshot: name is required")
	}
	if len(r.BatchIDs) == 0 {
		return NewError(CodeValidationInvalid, "snapshot: at least one batch_id is required")
	}
	for i, id := range r.BatchIDs {
		if id == "" {
			return NewError(CodeValidationInvalid, "snapshot: batch_ids[%d] is empty", i)
		}
	}
	return nil
}

// Validate checks the data query contract: snapshot pinned, as_of non-zero,
// replay_time non-zero when present, non-empty instruments and fields, valid
// range, bounded limit.
func (q DataQuery) Validate() error {
	if q.SnapshotID == "" {
		return NewError(CodeValidationInvalid, "data query: snapshot_id is required")
	}
	if q.AsOf.IsZero() {
		return NewError(CodeValidationInvalid, "data query: as_of is required")
	}
	if q.ReplayTime != nil && q.ReplayTime.IsZero() {
		return NewError(CodeValidationInvalid, "data query: replay_time must not be zero")
	}
	if q.Dataset == "" {
		return NewError(CodeValidationInvalid, "data query: dataset is required")
	}
	if q.Frequency == "" {
		return NewError(CodeValidationInvalid, "data query: frequency is required")
	}
	if len(q.InstrumentIDs) == 0 {
		return NewError(CodeValidationInvalid, "data query: instrument_ids is required")
	}
	if len(q.Fields) == 0 {
		return NewError(CodeValidationInvalid, "data query: fields is required")
	}
	if _, err := NewInterval(q.Range.From, q.Range.To); err != nil {
		return Wrap(err, CodeValidationInterval, "data query: range invalid")
	}
	if q.Limit < 0 {
		return NewError(CodeValidationInvalid, "data query: limit must be non-negative")
	}
	return nil
}

type Connection struct {
	ID        ID              `json:"id"`
	Version   string          `json:"version"`
	ParentID  ID              `json:"parent_id,omitempty"`
	Name      string          `json:"name"`
	Provider  VersionRef      `json:"provider_ref"`
	Settings  json.RawMessage `json:"settings"`
	SecretRef string          `json:"secret_ref,omitempty"`
	CreatedAt time.Time       `json:"created_at"`
}

func (c Connection) ToConfig() ConnectionConfig {
	return ConnectionConfig{
		Ref:       VersionRef{ID: c.ID, Version: c.Version},
		Provider:  c.Provider,
		Name:      c.Name,
		Settings:  c.Settings,
		SecretRef: c.SecretRef,
		ParentID:  c.ParentID.String(),
	}
}

func (c ConnectionConfig) Validate() error {
	if c.Name == "" {
		return NewError(CodeValidationInvalid, "connection: name is required")
	}
	if err := c.Provider.Validate(); err != nil {
		return Wrap(err, CodeValidationInvalid, "connection: provider_ref invalid")
	}
	if len(c.Settings) == 0 {
		return NewError(CodeValidationInvalid, "connection: settings is required")
	}
	probe := map[string]json.RawMessage{}
	if err := json.Unmarshal(c.Settings, &probe); err != nil || probe == nil {
		return Wrap(err, CodeValidationInvalid, "connection: settings must be a JSON object")
	}
	return nil
}

type Mapping struct {
	SourceField string `json:"source_field"`
	TargetField string `json:"target_field"`
	SourceUnit  string `json:"source_unit"`
	TargetUnit  string `json:"target_unit"`
	Scale       string `json:"scale"`
}

func (m Mapping) Validate() error {
	if m.SourceField == "" || m.TargetField == "" || m.SourceUnit == "" || m.TargetUnit == "" {
		return NewError(CodeValidationInvalid,
			"mapping: source_field, target_field, source_unit and target_unit are required")
	}
	if _, err := ParseDecimal(m.Scale); err != nil {
		return Wrap(err, CodeValidationDecimal, "mapping: scale invalid")
	}
	return nil
}

type IngestionRequest struct {
	ConnectionRef         *VersionRef `json:"connection_ref,omitempty"`
	ImportID              string      `json:"import_id,omitempty"`
	Dataset               string      `json:"dataset"`
	Frequency             string      `json:"frequency"`
	InstrumentIDs         []ID        `json:"instrument_ids"`
	Range                 Interval    `json:"range"`
	Mode                  IngestMode  `json:"mode"`
	Mapping               []Mapping   `json:"mapping"`
	Timezone              string      `json:"timezone"`
	AvailabilityPolicyRef VersionRef  `json:"availability_policy_ref"`
}

func (r IngestionRequest) Validate() error {
	if (r.ConnectionRef == nil) == (r.ImportID == "") {
		return NewError(CodeValidationInvalid,
			"ingestion: exactly one of connection_ref or import_id is required")
	}
	if r.ImportID != "" && len(r.ImportID) > 128 {
		return NewError(CodeValidationInvalid, "ingestion: import_id must be at most 128 characters")
	}
	if r.Dataset == "" {
		return NewError(CodeValidationInvalid, "ingestion: dataset is required")
	}
	if r.Frequency == "" {
		return NewError(CodeValidationInvalid, "ingestion: frequency is required")
	}
	if len(r.InstrumentIDs) == 0 {
		return NewError(CodeValidationInvalid, "ingestion: instrument_ids is required")
	}
	for i, id := range r.InstrumentIDs {
		if id == "" {
			return NewError(CodeValidationInvalid, "ingestion: instrument_ids[%d] is empty", i)
		}
	}
	if _, err := NewInterval(r.Range.From, r.Range.To); err != nil {
		return Wrap(err, CodeValidationInterval, "ingestion: range invalid")
	}
	switch r.Mode {
	case IngestIncremental, IngestBackfill, IngestForce:
	default:
		return NewError(CodeValidationInvalid,
			"ingestion: mode must be one of: incremental, backfill, force")
	}
	if len(r.Mapping) == 0 {
		return NewError(CodeValidationInvalid, "ingestion: mapping is required")
	}
	for i := range r.Mapping {
		if err := r.Mapping[i].Validate(); err != nil {
			return Wrap(err, CodeValidationInvalid, "ingestion: mapping[%d] invalid", i)
		}
	}
	if _, err := LoadBusinessTimezone(r.Timezone); err != nil {
		return err
	}
	if err := r.AvailabilityPolicyRef.Validate(); err != nil {
		return Wrap(err, CodeValidationInvalid, "ingestion: availability_policy_ref invalid")
	}
	return nil
}
